# Generated by Django 5.2.dev20241007133657 on 2024-11-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('PAID', 'paid'), ('DELIVERED', 'delivered')], default='PAID', max_length=20),
        ),
    ]
