# Generated by Django 5.2.dev20241007133657 on 2024-11-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('PAID', 'paid'), ('DELIVERED', 'delivered')], default='PENDING', max_length=20),
        ),
    ]
