# Generated by Django 5.2.dev20241007133657 on 2024-11-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_remove_payment_payment_date_order_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
