# Generated by Django 5.2.dev20241007133657 on 2024-12-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_order_is_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_processed',
            field=models.BooleanField(default=True),
        ),
    ]
