# Generated by Django 5.2.dev20241007133657 on 2024-12-06 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0023_payment_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='product',
        ),
    ]
